### ISSUE TITLE
Find out hotel APIs

### ISSUE THREAD

**Issue by rvegas** [asikrandev/trippr#1]
Look for best hotel apis. find out what we need (params, license, etc)
https://support.google.com/hotelprices/answer/6079219?hl=en

**Comment by asikranjm** [comment]
There are some free apis that i found that could work easily in our app.

Expedia Affiliate Network

Use the EAN API to build and grow a profitable travel business selling hotel reservations:

Organize and style content to suit your own business model
Full design control and the ability to brand content as your own
Build a site that is fully API-dependent or a combination of API and pre-programmed affiliate template pages
Flexibility to optimize your site for SEO and SEM benefits
Add your own content or combine with other content sources

http://developer.ean.com/

**Comment by asikranjm** [comment]
Google Hotel Api, I think this is the best api we can use because of the functions that it have.

HOTEL PRICES - FEEDS & APIS
Hotels API

https://support.google.com/hotelprices/answer/6079219?hl=en&ref_topic=6076540

**Comment by asikranjm** [comment]
Tixik

3 reasons why use TIXIK.com API
We ar focused on travel and tourism. You don't have to filter out texts about universities or gas stations, for example.
Tixik.com data do not comprise advertisements. No hotels, no car rentals, just clean data for your non-commercial or commercial  travel application.
It's free.
Requirements
Every page, that is using TIXIK.com data, must provide a visible backlink to TIXIK.com. 

http://www.tixik.com/info/api/

http://www.tixik.com

**Comment by rvegas** [comment]
Cool cool

**Comment by asikranjm** [comment]
Yahoo tiene una pero por alguna razón ahorita esta como bloqueada asi que gg.

**Comment by asikranjm** [comment]
Drupal.org they have an api for booking.com

Looks very Awesome! seems it works with xml coding.

https://www.drupal.org/project/booking_com_api

https://www.freelancer.com/projects/PHP-XML/Booking-com-XML.1266741.html

**Comment by rvegas** [comment]
closing as resolved - we will choose later
