### ISSUE TITLE
Setup and run a Webrtc listener in nodejs

### ISSUE THREAD

**Issue by rvegas** [asikrandev/trippr#5]
use js to have a server always listening for webrtc requests and autoresponding

**Comment by jegasmlm** [comment]
git clone https://github.com/joyent/node.git
cd node
git checkout v0.6.18 #Try checking nodejs.org for what the stable version is
./configure && make && sudo make install

**Comment by rvegas** [comment]
we had to use native js for now. contacted acision in the meantime.
